name : dify

services:
  dod-app:
    image: zfanswer/dify-on-dingtalk:latest
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./.bots.yaml:/app/.bots.yaml
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
